### ISSUE TITLE
Modern Techniques for Writing Better CSS

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#126]

**Comment by ted-dino** [comment]
Awesome content! Looking forward for more

**Comment by kyds3k** [comment]
Bookmarked! This is awesome!

**Comment by MazontheMoon** [comment]
Great read!

**Comment by kishoreandra** [comment]
Amazing read !! clamp one is great and chaining selectors ....

**Comment by vadiks2003** [comment]
haha, i like how this article was made on CSS and it tells about CSS stuff, and so we can see stuff like "clamp" used in action and see it in the inspect code. i was too lazy to read the entire thing, i would forget 90% of it anyways... however still this one is useful

**Comment by WebDragon** [comment]
ok so I was playing around earlier and conceived of this little bit of sexyness
```css
:required:where( input, textarea ):where( :placeholder-shown, :invalid ) {
    border-color: var(--warning);
}
```
and I just ...  the calisthenics I would have had to go through to unpack and achieve that previously...
