### ISSUE TITLE
Creating a Fluid Type Scale with CSS Clamp

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [AleksandrHovhannisyan/aleksandrhovhannisyan.com#131]

**Comment by solution-loisir** [comment]
First of all, thanks for such a detailed and overall high quality write up. I've been experimenting lately with fluid types and fluid design in general. Funny enough, the following idea yield some pretty good results and is less complex than what I've seen in the wild and in tutorials.
```scss
$font-h1: 2em;
$font-h2: 1.7em;
$font-h3: 1.2em;
$font-base: clamp(1.08rem , 0.46vw + 0.9rem, 1.2rem);
```
```scss
body {
  font-size: $font-base;
}

h1 {
  font-size: $font-h1;
}

h2 {
  font-size: $font-h2;
}

h3 {
  font-size: $font-h3;
}
```
Now the headings are relative to the font base which is fluid with a very slight variation. I'd like to engage discussion over such concept versus clamping everything. Have a good day!

**Comment by AleksandrHovhannisyan** [comment]
@solution-loisir Thanks! I actually agree—while I've found clamping to be nice for font sizing, it's a little awkward for other properties. I used to clamp my spacing variables at one point, but now I maintain a separate set of pixel measurements that I use for margins/padding/borders/etc.

Using ems like that is clever! Generally, though, it's not recommended to use `em`s for font sizing because it can lead to compounding effects if you apply it to deeply nested components whose parents also use `em`-based font sizes. (More on that here: https://www.aleksandrhovhannisyan.com/blog/use-rems-for-font-size/#a-first-attempt-with-em). This wouldn't be an issue in the code you shared because you'd never nest headings.

Personally, I also don't like the idea of tying down the font sizes to heading levels because it may lead to misuse of headings for font sizing. In my opinion, the ideal approach is to have a set of reusable font size variables and use them to style your headings by default, but then also have a separate set of font size utility classes (like `.fs-sm`, `.fs-base`, `.fs-md`, etc.) that can be used as needed. I do this on my site. For example, in some cases, I want to use a certain heading level for semantics but change its font size to be larger or smaller than the default.

**Comment by solution-loisir** [comment]
Thanks for the quick reply! As I read, I realized that my knowledge on `em` and `rem` was incomplete and went on a reading to clarify things up. It made me realized that I could use the same idea but with `rem`s instead. Something like this:
```scss
$base-size: 1rem;

// Variable names and overall scaling system borrowed from Andy Bell's Gorko tool.
// https://github.com/hankchizljaw/gorko 
$size-300: $base-size * 0.8;
$size-400: $base-size * 1;
$size-500: $base-size * 1.2;
$size-600: $base-size * 1.7;
$size-700: $base-size * 2;
$size-800: $base-size * 2.4;

// Fonts
$font-base-size: clamp(#{$size-500} * 0.9, 0.46vw + 0.91rem, #{$size-500});
```
The base font size as to be declared on the root element though.
```scss
html {
  font-size: $font-base-size;
}

h1 {
  font-size: tokens.$size-700;
}
h2 {
  font-size: tokens.$size-600;
}
h3 {
  font-size: tokens.$size-500;
}
```
Now every sizes are relative to `font-base-size` and can be used without the 'limitations' of `em`s. I don't think it is a new idea. More of a fluid version of:
```scss
html {
  font-size: 1.08rem;
  @media(min-width: $md) {
    font-size: 1.2rem;
  }
}
```
Anyhow, this is just me tinkering on my side project. Thank again for all your input!

**Comment by AleksandrHovhannisyan** [comment]
@solution-loisir I thought about this a bit more, and I think something like this would also work:

```css
  --type-scale: <pick a ratio>;
  --fs-xs: calc(var(--fs-sm) / var(--type-scale));
  --fs-sm: calc(var(--fs-base) / var(--type-scale));
  --fs-base: clamp(1rem, 0.34vw + 0.91rem, 1.19rem);
  --fs-md: calc(var(--fs-base) * var(--type-scale));
  --fs-lg: calc(var(--fs-md) * var(--type-scale));
  --fs-xl: calc(var(--fs-lg) * var(--type-scale));
  --fs-2xl: calc(var(--fs-xl) * var(--type-scale));
  --fs-3xl: calc(var(--fs-2xl) * var(--type-scale));
  --fs-4xl: calc(var(--fs-3xl) * var(--type-scale));
  --fs-5xl: calc(var(--fs-4xl) * var(--type-scale));

  @media screen and (min-width: desktop) {
    --type-scale: <pick a ratio>;
  }
```

You could also use CSS variables to derive the base clamp so it's not hard-coded. Going to think about this some more and potentially update the post and/or https://fluid-type-scale.com/.

**Comment by yababay** [comment]
Hi, Alexandr, thank you for the great article. It became very useful for me.

It's seems there is an misprint. It should be written `--font-size-sm: clamped(13.33px, 16px);...` instead of `--font-size-sm: clamp(13.33px, 16px);...` in "Native Approach..." section.

All the best to you!

**Comment by AleksandrHovhannisyan** [comment]
@yababay Good catch, thanks! I'll push up a fix later today.

**Comment by NiklasGameDev** [comment]
Sorry if this a dumbass question but I have been trying to implement this into my project for days now without success.
I am no web genius at all so after reading multiple articels on fluid typography and its formulas, I am left with only one question:
Is it even possible to dynamically calculate the preffered value in regular css ?

I tried calculating all values without units and then multiplying the slope with 100vw and the intercept with 0.1rem because I am using a Rem-value of 10px. I need an explanation or my head is going to explode :(

**Comment by AleksandrHovhannisyan** [comment]
@NiklasGameDev Andy Bell wrote this a few years ago. It uses unitless values to ensure CSS calc works correctly for the interpolation: https://archive.hankchizljaw.com/wrote/custom-property-controlled-fluid-type-sizing/

**Comment by yababay** [comment]
Hi, NiklasGameDev, you can see working example [here](https://github.com/yababay/evhome).

**Comment by NiklasGameDev** [comment]
I have seen this formula before in a few articles but it never worked. This one actually did work so thanks for linking it.

**Comment by bearoxo** [comment]
Inverted min max value.

![image](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/assets/53261024/e713a19f-88eb-4af6-ac29-fffe762be234)

https://www.desmos.com/calculator/afxjle1b3d

**Comment by AleksandrHovhannisyan** [comment]
@bearoxo It might be worth moving that discussion to the project's repo as an issue: github.com/AleksandrHovhannisyan/fluid-type-scale-calculator/

That said, this is technically working as expected from a math standpoint. For example, on your graph, notice how the red curve is above the blue curve at `x = -3` (corresponding to the `xxs` step in your screenshot above):

![Comparing the curves f(x) = 16*1.25^x, red, and g(x) = 19*1.333^x, blue, at x = -3](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/assets/19352442/c3d58050-5457-4397-b38a-8bc44e3a364b)

However, I also see that comparable tools like Utopia just flip the min and max values: https://utopia.fyi/type/calculator/?c=400,16,1.25,1280,19,1.333,5,3,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12. I _could_ do the same, but it technically wouldn't be correct, as it would mean that the minimum would be using the 1.333 type scale rather than 1.25 at that step.

**Comment by bearoxo** [comment]
Ah, I see. So that intersection point is the smallest font-size where the font can shrink to.

**Comment by bearoxo** [comment]
It's 2AM now and my brain is potato. But I think I get it now, that intersection point is where the fluid scaling starts working its magic, before that point it'll shrink the font size but will still max at the red curve.

**Comment by AleksandrHovhannisyan** [comment]
@bearoxo Correct. My tool doesn't currently add any warnings/alerts if you accidentally go past that inflection point; I'm not sure what the level of effort would be for that. Also, as a general rule of thumb, you don't want too many negative steps to your type scale since the font sizes will be illegibly small (in this case, ~8px, while the minimum recommended for the web is usually 12px).

**Comment by proimage** [comment]
This is a great write-up, and goes a long way to helping me figure things out. However, I've got an additional wrinkle, and I just can't figure out how to adjust the formula accordingly.

I'm working on a Tailwind site, and the client wants basically the entire site to scale up vaguely linearly with the browser size. So padding, margins, gaps, everything should scale.

They also have specific font-sizes for the smallest designed viewport (320px) and the largest one (1920px), even though the site should continue to scale beyond the largest one. Don't ask. 🤷 

Anyway, to accomplish this scaling, I found that adjusting the font-size on the `<html>` element does the trick. So what I have now is this:
```scss
html {
	font-size: clamp(0.75rem, 0.6rem + 0.75vw, 1.5rem);
	@media (min-width: 1920px) {
		font-size: 1.25vw;
	}
}
```
This is a scale of 12px @ 320px wide to 24px at 1920px wide, and then just a linear scale beyond that.

I then scale the various headings with their own sizing, for example:

```scss
// H3 - 24-100px @ 320-1920w
h3 {
    font-size: clamp(2rem, 1.567rem + 3.25vw, 4.167rem);
}
```

The issue is that this scaling of the actual `rem` value makes all these clamp calculators and formulae invalid. At the lower bound, 1rem = 12px, but at the upper, it's 24px. Now, I can _manually_ adjust the lower and upper bounds without a problem... 24px when 1rem = 12px is simply 2rem, and 100px when 1rem = 24px is 4.167rem.

But I can't wrap my head around the `preferred` value calculation. How would I adjust the formula to account for this changing rem value?
